### ISSUE TITLE
vk header transitions swapchain images without first acquiring them

### ISSUE THREAD

**Issue by ratchetfreak** [chaoticbob/tinyrenderers#2]
This isn't allowed every swapchain image must be acquired before you can do any access with it.

Instead you can set the initial layout to undefined instead of present after acquiring them in the render loop. It is always valid to put undefined as the initial layout in a transition if you don't care about preserving the data.

**Comment by chaoticbob** [comment]
Are the validation layers complaining about this?

**Comment by ratchetfreak** [comment]
not yet but they should. It's an open issue last I checked.

**Comment by chaoticbob** [comment]
Cool, I will rectify this ASAP

**Comment by chaoticbob** [comment]
This should be fixed now.
