### ISSUE TITLE
Vulkan barrier stages are wrong

### ISSUE THREAD

**Issue by Themaister** [chaoticbob/tinyrenderers#3]
BOTTOM_OF_PIPE/TOP_OF_PIPE are used with srcAccessMask/dstAccessMask != 0. These stages do not access memory, so any memory barrier on these stages is wrong. ALL_COMMANDS_BIT -> ALL_COMMANDS_BIT would accomplish the same thing.

**Comment by chaoticbob** [comment]
I've made the suggested change.
